### ISSUE TITLE
EID comments not being displayed correctly

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#1095]
The comments on this [EID](https://civicdb.org/evidence/8177/summary) appear blank. When looking in the Event feed I can see that two comments have been submitted and when I mouse-over the tags it displays the comments text that is missing from the Comments section.

![image](https://github.com/user-attachments/assets/62718dc9-ed11-41bd-beb5-975838877b00)

![image](https://github.com/user-attachments/assets/a87ea671-f8ab-4764-99f6-1e82055369f1)

**Comment by acoffman** [comment]
Thanks for the report, that's definitely strange; we'll take a look!

**Comment by acoffman** [comment]
This turned out to be an issue with caching the parsed comment bodies across a schema change. It should be fixed now.

I have also opened A PR to slightly improve the display of the top "Submission Comment" when the submitter did not provide one (which is the case here).

Thanks again for the report!

**Comment by cgrisdale** [comment]
Thanks for getting this fix out so quickly.
