### ISSUE TITLE
Remove field value debugging output at bottom of forms before go-live

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-v2#349]
using Chrome on OS Catalina.
<img width="1439" alt="code" src="https://user-images.githubusercontent.com/13948978/161291186-a9126bfb-704d-4bff-b2e7-dac20e540a04.png">

**Comment by obigriffith** [comment]
I think this is intentional. But, I had the same instinct/reaction at first. Like when you see code like this you might think the page/form is broken. I think this could be solved by adding some visual clue that this belongs. Like putting it in a box, maybe collapsed by default, with a heading/title to explain what you are looking at.

**Comment by susannasiebert** [comment]
This is just for easier debugging during this testing portion before release. It will be removed before go-live
