### ISSUE TITLE
Improve default display when no NCCN guildeline is provided

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#474]
<img width="1509" alt="Screen Shot 2022-04-18 at 2 42 37 PM" src="https://user-images.githubusercontent.com/8527125/163867197-7fb992c6-af9f-4e94-8111-5bf89298c262.png">

Currently the display is () for what I believe is an AID without an NCCN guideline associated. I don't know off what is the preferred language for when an entity has not been provided yet but can be curated.

**Comment by susannasiebert** [comment]
This is actually an odd case, where the assertion is associated with an actual nccn guideline object in the database, which has a name of `""`. I think we might just want to delete this nccn guideline, since I doubt we meant to create it in the first place. I wonder if you would be able to remove this nccn guideline through the edit assertion form.

**Comment by susannasiebert** [comment]
I fixed the underlying data issue. The NCCN guideline now show as `None Provided`.
