### ISSUE TITLE
Cannot return null for non-nullable field EvidenceItem.source

### ISSUE THREAD

**Issue by creisle** [griffithlab/civic-v2#480]
I ran into the following error querying the graphql API for civic v2

```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable field EvidenceItem.source"
    }
  ]
}
```

To reproduce the error you can use the following query

url: https://civicdb.org/api/graphql
query body

```graphql
query evidenceItems($after: String) {
  evidenceItems(after: $after) {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    nodes {
      id
      status
      variant {
        name
        id
        variantTypes {
          name
          soid
        }
      }
      gene {
        name
        id
      }
      evidenceType
      evidenceLevel
      evidenceRating
      evidenceDirection
      phenotypes {
        id
        hpoId
        name
      }
      description
      disease {
        id
        doid
        name
        diseaseAliases
        displayName
      }
      drugs {
        id
        ncitId
        name
        drugAliases
      }
      source {
        ascoAbstractId
        citationId
        pmcId
        sourceType
        title
      }
      drugInteractionType
      lastAcceptedRevisionEvent {
        createdAt
      }
      lastSubmittedRevisionEvent {
        createdAt
      }
    }
  }
}
```

variables
```json
{
  "after": "NzUw"
}
```

**Comment by acoffman** [comment]
Hi @creisle thanks for the report!

We added a lot stricter data validation in V2, and its definitely catching some weird stuff that fell through the cracks in V1. In this case, the culprit is an Evidence Item that was never completed, and left in an invalid state (missing a Source as the error states.) It was soft-deleted but never fully cleaned up. 

I've tested your query and you should be good to go now. Please let us know if you encounter any more issues though!

**Comment by creisle** [comment]
Thanks for addressing this so quickly, everything appears to work from my end now as well!
