### ISSUE TITLE
Adding text to grid column filter sometimes causes page freeze

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#524]
When adding text into the column filter at the top of Evidence/Gene/Source/etc grids, sometimes I get the rotating blue circles as if the page is trying to load, but it never finishes loading. The only way to resolve it is to navigate to a different page or hard refresh.
This seems to happen when I've added part of the text I want to filter on and the grid starts filtering, then I add more text or click away. It can also be reproduced by continuing to add text when there are already no filter results.

![image](https://user-images.githubusercontent.com/3093548/167011470-6419e1f2-4619-4d3d-a2bf-5c2e26fb5f2b.png)

![image](https://user-images.githubusercontent.com/3093548/167011678-5a60914c-8ea9-4e04-aee5-c7521b22e657.png)

**Comment by jmcmichael** [comment]
I think I figured out the issue:
- the tables are populated by the observable from `queryRef.valueChanges`, which will only update the table if the actual returned results differ from the previous result set
- we hack apollo-angular's lack of an initial `isLoading: true` value by setting `this.isLoading = true`  and then setting it back to false in a subscription function that's called when `queryRef.valueChanges` is updated
- when two queries are made that return the same results, the refresh function sets `isLoading = true`, but since the results are identical, `queryRef.valueChanges` does not fire, and `isLoading = false` is never evaluated, so the spinner overlay is never removed
