### ISSUE TITLE
Not able to save suggestion revision to AID20

### ISSUE THREAD

**Issue by gaberudy** [griffithlab/civic-v2#532]
Hello, I am having issues using the "Revision" page for BRAF V600E prognosis assessment.

This record has a "Yes" for companion diagnostic, but it should be No, given the FDA Regulatory Approval value is correctly set to no (there is no drug association with this record).

I tried to suggest this revision, but I receive an error message on save.

![image](https://user-images.githubusercontent.com/872263/169354561-06762633-c716-4c64-8c1a-35925220ec2a.png)

**Comment by acoffman** [comment]
Hi, @gaberudy thanks for the detailed report.

The issue here is that `FDA Regulatory Approval` actually has three possible values, Yes, No, and Undefined. The validation is working "as intended" in that Assertions without drugs cannot have FDA Regulatory Approval but the form behavior is confusing. 

The intention is that "No" means "It is possible that there would be FDA Approval but there is not in this case" whereas the undefined case is essentially "Not Applicable for this"

If you select the blank option, it should allow you to submit the revision, but I agree this is confusing and not the intended UX. We will discuss how to make that form more intuitive and I'll follow up here.

**Comment by gaberudy** [comment]
@acoffman Ok, thanks for the clarification.

You may consider having the options be Yes, No, N/A

Note also that by changing it to "Blank" the companion diagnostic option was hidden. The reason I am attempting to edit this entry to set the companion diagnostic entry to No or Blank, because it is confusing that it is set to Yes when the regulatory approval is No.

I was able to make a revision request, but we will see if it resulted in both fields are now undefined, which I believe is the correct state for a prognostic entry.

**Comment by acoffman** [comment]
Yep, totally agreed this is not ideal. In the normal path through the form you simply won't be presented with either option for Prognostic assertions and we handle it correctly on the backend, but in this case where the Assertion is already in an unexpected state, its behaving in an intuitive way. Definitely not how we want it to work.
