### ISSUE TITLE
Revise evidence form should not ask for Disease when evidence type == functional

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-v2#582]
When I go to add evidence and select `Evidence Type` -> `Functional`.  There is no disease.  I believe this is as expected.  

But, when I go to **revise** a `Functional` evidence item, I am presented with the ability to add a disease.  It shows as optional but I think we do not want it shown there?

On the staging server I actually tried adding one here: https://staging.civicdb.org/evidence/9948/revise/suggest

And it gives me an error that makes sense: `Validation failed: 'Disease' Disease cannot be set for Functional evidence type`

So I think we just want to remove disease from the revise evidence form (when evidence type is functional)?

**Comment by acoffman** [comment]
@malachig We investigated this today and had some follow up questions.

We are indeed validating that functional evidence does not have a disease, and you are not able to submit new evidence with a disease or revise one to have a disease (as you noted.)

However, there are still 120 Functional EIDs that have a disease set, I believe we will need to decide what to do with them before hiding the "Disease" form control for revisions, otherwise people will not be able to propose revisions to remove the disease.

@susannasiebert And I think there are really two possible solutions here:

1. Since this isn't really a "data change" but the removal of a field, we can just drop diseases from all Functional evidence unilaterally.
2. We can just go through and propose a change to each of the 120 eids manually to remove the disease/or have civicbot do it

As an additional wrinkle, I believe we had planned to move some of these EIDs from Functional -> Oncogenic, which makes option 1 above sub optimal. Really, editors probably need to go look at each of these.

In spite of all this we _can_ hide the disease form field for revising functional evidence, which will result in any proposed revision also automatically proposing to remove the disease. This would work but we feel it might be confusing for users that submit a revision and then see a revision attributed to them (Disease Name -> N/A) that they did not propose explicitly.
