### ISSUE TITLE
MP Pre-release fixups

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-v2#600]
- [x] evidence score move from variants to MPs (browse table/view)
- [x] reject open revisions (or generate a report, or make a new revision) moving eids between variants
- [x] remove evidence, score, assertion counts, etc from variant browse table
- [x] Add evidence button from molecular profile page
- [x] we need help text for MP input form
- [x] comment stuff not working? (include support for linking to MPs when fixing)
- [x] TSV creation molecular profiles (and updating EID/Variant tsv fields)
- [x] Load MP into submit form from source suggestions and "add evidence" button
- [x] Verify that the event feed still works
- [x] Verify that the notifications work
- [x] Update civicpy 
- [x] Remove variant description

**Comment by acoffman** [comment]
List of EIDs with outstanding variant move revisions: https://gist.github.com/acoffman/9ec4f4d96467d4dfd9e5ae3344443e3b

**Comment by ahwagner** [comment]
Adding to this issue since this seems to be the release mega-thread:

One feature enhancement request. When selecting "complex molecular profile" or "simple molecular profile" on the new evidence form on staging.civicdb.org (shown below), the transition is slow enough that I thought the feature was broken. Would it be possible to speed this up prior to release?

![image](https://user-images.githubusercontent.com/811065/189436324-1ca5c4ad-ac91-40ec-bbf0-a74e8c6ddc90.png)
