### ISSUE TITLE
Duplicate variants and molecular profiles

### ISSUE THREAD

**Issue by korikuzma** [griffithlab/civic-v2#863]
[This](https://github.com/griffithlab/civic-v2/pull/774) PR was created to prevent duplicate names on variants and molecular profiles. However, we're still seeing duplicates. Here are the duplicate variants (only looked at accepted or submitted) we are seeing:

```json
{
  "ERBB2 A775_G776insYVMA": [2658, 4483],
  "ERBB2 L755P": [1304, 4490],
  "BRAF V600D": [11, 3452],
  "BRAF V600R": [16, 991]
}
```

**Comment by acoffman** [comment]
Thanks for the report! There is some additional context in #864 but we had to temporarily remove that validation. I've now reworked it and added it back.

That being said, looking at the timestamps it would appear that most of these were created prior to that validation existing anyways. The additional validation will not do anything to resolve these automatically, a curator or editor will need to go in and propose edits to the EIDs to move them so that the Variants can be deprecated.

I see you've flagged some of these, and I will bring these up in the slack channel to try and draw some curator attention to them as well.
