### ISSUE TITLE
Cannot add new variant when text exists in another variant

### ISSUE THREAD

**Issue by refu6enik** [griffithlab/civic-v2#890]
This issue is similar to https://github.com/griffithlab/civic-v2/issues/888

Several molecular profiles for Chronic Myeloid Leukemia are in the wrong format https://civicdb.org/diseases/4/summary, being <variant #1 actually representing 2 variants>.

For example,
1. https://civicdb.org/molecular-profiles/866/summary
2. https://civicdb.org/molecular-profiles/995/summary

When I attempt to revise the evidence to update the molecular profile to be <variant #2> AND <variant #3>, one of the variant names is contained in variant #1 name, and I am not able to add the correct variant.

**Comment by acoffman** [comment]
Hi,

Thanks for reporting this!

Due to the way the various autocomplete components are set up, they won't display the "Add New" form unless there are no results from the typeahead.

As you've noticed, that doesn't work well for Variants. We have a fix in progress and it'll be out in the next release. I'll follow up here when that happens, hopefully within the next day or two.
