### ISSUE TITLE
Accepted variants missing from TSV monthly releases

### ISSUE THREAD

**Issue by fescudie** [griffithlab/civic-v2#928]
Hi and thanks for your work.

I use Evidences TSV and Variants TSV releases from https://civicdb.org/releases/main. Unfortunately, some variants reported in accepted evidences do not appear in the variants file.

Example: variant [13](https://civicdb.org/api/variants/13) for evidence [73](https://civicdb.org/api/evidence_items/73) in TSV of 01-Oct-2023.
```
user@computer clinical_evidences # grep "\s4170\s" CIViC_ClinicalEvidenceSummaries_01-Oct-2023.tsv
BRAF V600E AND BRAF V600M       4170    Melanoma        1909            Dabrafenib              Predictive      Supports        C       Sensitivity/Response    A single 66-year old male patient with advanced melanoma thought to have concomitant BRAF V600E and V600M mutations responded rapidly to dabrafenib. His shoulder lesion reduced by 60% after 1 week of therapy and was gone after 1 month.   23031422     PubMed           Ponti et al., 2012, J Hematol Oncol             1       accepted        73      Somatic 2023-01-11 17:59:40 UTC https://civicdb.org/links/evidence_items/73     https://civicdb.org/links/molecular_profiles/4170     false
user@computer clinical_evidences # grep "^13\s" CIViC_VariantSummaries_01-Oct-2023.tsv
user@computer clinical_evidences # grep "\s4170\s" CIViC_VariantSummaries_01-Oct-2023.tsv
user@computer clinical_evidences #
```

From what I understand from reading the documentation ("[Variant TSV releases only include variant records with accepted evidence records`](https://civicdb.org/releases/main)"), this seems to be unexpected behavior. Is it possible to correct it ?

**Comment by acoffman** [comment]
Hi, thanks for your interest in CIViC!

The Variant in question: https://civicdb.org/variants/13/ has been deprecated and its associated evidence moved to a new Molecular Profile: https://civicdb.org/evidence/73. That is why it is not appearing in the TSV.

It looks like you're posting links to the old V1 API; this API has been deprecated and operating off of a static copy of CIViC data for over a year now and will be decommissioned in November. This explains why you are not seeing the changes to the data that are reflected in the TSV downloads.

It is highly recommended to switch to the new GraphQL API (playground available here: https://civicdb.org/api/graphiql) which is still free, open access, and will provide access to the latest data and data model. 

If you need help porting an existing script to the new API feel free to respond here or email us at help@civicdb.org and we'd be happy to offer some pointers, or answer any questions about changes to the CIViC data model since V2 came out.
